### ISSUE TITLE
does it work on win11 & with python 3.1

### ISSUE THREAD

**Issue by Vik1922** [msrouter/windwostorvpn#1]
hi has anyone installed it on win11 & has anyone used a python 3.1 with it. thanks in adv!

**Comment by Xsenix69** [comment]
I get the following error when I first came across this repository
`
Traceback (most recent call last):
  File "C:\windowstorvpn\tor_services.py", line 4, in <module>
    from proxy import Proxy
  File "C:\windowstorvpn\proxy\__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "C:\windowstorvpn\proxy\proxy.py", line 9, in <module>
    from . import socks
  File "C:\windowstorvpn\proxy\socks\__init__.py", line 1, in <module>
    from .socks import *
  File "C:\windowstorvpn\proxy\socks\socks.py", line 62, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (C:\Python312\Lib\collections\__init__.py)
`
The problem is solved simply:
**in 62 line** `from collections import Callable`
**replace to** `from collections.abc import Callable`
because Callable has been moved from collections to collections.abc starting with Python 3.3
